variables:
  AWS_DEFAULT_REGION: eu-central-1

test:
  before_script:
    - aws ecr get-login --no-include-email | sh
    - ./setup/start-dockercompose
    - ./setup/setup_kong.sh ./number-portability-sdk-tests
    - docker build . -t coin-sdk-dotnet
  script:
    - ./setup/start-dockercompose sdk
  after_script:
    - ./setup/stop-dockercompose