version: '2.4'

services:
  coin-sdk:
    build: .
    environment:
      - STUB_HOST_AND_PORT=kong:8000
    depends_on:
      kong:
        condition: service_healthy
      setup:
        condition: service_started
    networks:
      - kong-network

networks:
  kong-network: