#!/bin/bash

# remove port exposure to avoid conflicts
sed -e 's/"[0-9][0-9]*:\([0-9][0-9]*\)"/"\1"/g' docker-compose.yaml > /tmp/docker-compose.yaml
docker-compose --project-name coin-sdk-dotnet-${CI_JOB_ID} --file /tmp/docker-compose.yaml --project-directory ${PWD} up -d --build